export const routes = {
  home: "/home",
  about: "/about",
  contact: "/contact",
  test: "/test",
  typography: "/typography",
  buttons: "/buttons",
  inputs: "/inputs",
  chips: "/chips",
  progress: "/progress",
  dropdown: "/dropdown",
  stepper: "/stepper",
  calendar: "/calendar",
  calendar2: "/calendar2",
};
